import { AlertSeverity } from './alert-severity.value-object';

/**
 * Represents the alert generated by an incident.
 */
export class Alert {
  /**
   * The identification of the alert.
   */
  private _id: number;
  /**
   * The message of the alert.
   */
  private _message: string;
  /**
   * The severity of the alert.
   */
  private _severity: AlertSeverity;
  /**
   * Tells if the alert has already been read.
   */
  private _isRead: boolean;
  /**
   * The generation date of the alert.
   */
  private _generatedAt: Date;

  constructor(alert: { id: number; message: string; severity: AlertSeverity; isRead: boolean; generatedAt: Date }) {
    this._id = alert.id;
    this._message = alert.message;
    this._severity = alert.severity;
    this._isRead = alert.isRead;
    this._generatedAt = alert.generatedAt;
  }

  /**
   * Marks the alert as read.
   */
  markAsRead(): void {
    this._isRead = true;
  }

  get id(): number {
    return this._id;
  }

  set id(value: number) {
    this._id = value;
  }

  get message(): string {
    return this._message;
  }

  set message(value: string) {
    this._message = value;
  }

  get severity(): AlertSeverity {
    return this._severity;
  }

  set severity(value: AlertSeverity) {
    this._severity = value;
  }

  get isRead(): boolean {
    return this._isRead;
  }

  set isRead(value: boolean) {
    this._isRead = value;
  }

  get generatedAt(): Date {
    return this._generatedAt;
  }

  set generatedAt(value: Date) {
    this._generatedAt = value;
  }
}
